In [7]:
import torch
import numpy as np

In [2]:
inputDim = 3
outputClass = 5

In [ ]:
x_train = torch.randn(100, inputDim)
x_train

tensor([[-0.9992, -1.0085, -0.5559],
        [-0.0939,  0.1617, -0.2177],
        [ 0.5225,  1.6825,  0.8735],
        [-0.2795,  1.5697,  1.8176],
        [ 1.1866,  1.3620, -1.2273],
        [ 0.9822, -0.5387,  0.6029],
        [-0.6321, -1.3551,  0.3096],
        [-0.8033,  0.3631, -0.2004],
        [-0.3971,  1.2223,  0.4131],
        [ 0.2413,  0.8631,  0.5878],
        [-0.3530, -1.6474, -1.3048],
        [-1.1298, -2.0153, -0.2832],
        [ 0.7230,  0.8423,  1.2684],
        [ 1.3659, -0.8605, -0.5182],
        [-1.5457,  0.9634,  0.3460],
        [-0.9200, -1.1519,  0.1122],
        [-1.2952,  0.2268,  0.0997],
        [-0.4645,  0.5122,  0.0368],
        [ 1.1358, -0.0755,  0.0888],
        [-1.2135, -2.1322,  0.3042],
        [ 0.6995,  1.1918, -1.0813],
        [-1.5233, -0.3431,  1.1505],
        [ 0.0377,  0.6385,  2.2355],
        [-1.2191, -1.8762, -0.7135],
        [-0.8299,  1.1041, -0.7778],
        [ 0.5731,  0.2497,  0.3690],
        [-0.6618, -0.2215,  0.9376],
 

In [15]:
x = x_train.clone()
features = x.sum(dim=1)
i=1
y_train = torch.sin((2+i)*np.pi*features) + torch.cos((2+i)*np.pi*features) + 0.3 * features ** 2 + 0.1 * torch.randn_like(features)
y_train = y_train = y_train.unsqueeze(1)

In [14]:
y_train

tensor([ 3.2914, -0.7344,  1.4656,  1.3869,  1.1884, -1.0423,  0.1987,  1.3802,
         0.3435, -0.3361,  4.5069,  3.5683,  3.4338,  0.9860, -1.5080,  2.3580,
        -1.1031,  1.5088, -0.6260,  2.3275,  1.3655,  0.5666,  2.5524,  5.1020,
         1.0616, -0.1967,  1.4690,  3.3903,  0.3834,  1.9053,  1.3984,  1.1923,
         1.3148, -0.9379,  0.9577, -0.5226,  1.0060,  1.1475, -0.2532,  1.1808,
         1.6290,  0.1080,  1.1739, -0.9521, -0.0556,  1.9004,  2.0492,  0.9601,
        -1.0381,  1.2810, -0.5706,  1.3292,  0.8111, -0.2460, -0.6396, -0.1759,
         1.0004,  1.4501,  3.6459,  3.3318,  0.2682,  1.5986, -0.0302, -0.2897,
         0.0327,  1.3211,  4.1870,  0.6493,  2.4656,  0.9451,  0.2437,  1.9504,
         0.4438, -1.2267, -0.3505, -0.8880, -1.1438, -1.1099, -0.3779, -0.1430,
        -0.7613,  1.4157,  3.1160,  1.0661,  0.9943, -1.0668,  1.6928, -0.8899,
        -0.9539,  0.3185,  4.3643, -0.1527, -1.1105,  0.6925,  1.4023, -0.9101,
         2.0802,  2.3852,  0.7593,  1.83

In [18]:
x = x_train.clone()
features = x.sum(dim=1)
result = []
for i in range(0, outputClass):
    y_train = torch.sin((2+i)*np.pi*features) + torch.cos((2+i)*np.pi*features) + 0.3 * features ** 2 + 0.1 * torch.randn_like(features)
    result.append(y_train)  

In [44]:
all_vals = torch.stack(result, dim=0).T
sorted_idx = torch.argsort(all_vals, dim=1)
mid_pos = all_vals.shape[1] // 2
median_group = sorted_idx[:, mid_pos]

In [58]:
i=20

In [59]:
all_vals[i]

tensor([-0.4304,  1.4025, -1.3172,  1.2318, -0.2865])

In [60]:
sorted_idx[i]

tensor([2, 0, 4, 3, 1])

In [61]:
median_group[i]

tensor(4)

In [43]:
all_vals

tensor([[ 1.3515,  3.5661,  1.9436,  0.5393,  2.4986],
        [-0.1748, -1.0710, -1.2144, -1.2617, -1.3550],
        [ 4.0650,  1.2340,  4.1866,  1.4951,  4.0251],
        [ 4.2969,  1.6167,  3.9677,  2.1254,  3.3090],
        [ 0.8654,  1.5316, -1.0837,  1.0331,  1.2457],
        [ 1.6519, -0.9707,  1.6828, -0.9084,  1.6410],
        [ 1.1079, -0.1705, -0.6630,  0.2425,  1.6818],
        [ 0.1037,  1.3965, -1.0603, -0.0842,  1.5600],
        [ 1.3525,  0.2444, -0.3920,  1.8890, -0.6012],
        [-0.4358, -0.4549,  0.8049,  2.0758,  2.2992],
        [ 1.9839,  4.7670,  3.1978,  2.1863,  4.7721],
        [ 2.0696,  3.3132,  4.8062,  3.0335,  2.3137],
        [ 2.0875,  3.5614,  1.1772,  3.8584,  1.4010],
        [ 1.0474,  0.9537,  0.7595,  0.8154,  0.6243],
        [-0.9424, -1.4907, -1.2676, -0.4503,  0.7997],
        [ 2.3484,  2.4984,  2.4788,  2.5658,  2.5734],
        [ 1.3070, -0.8264,  1.5332, -1.1675,  1.6904],
        [ 1.3156,  1.2775,  1.4020,  1.1431,  0.9869],
        [ 