In [1]:
import numpy as np
import math

In [2]:
word_SOS = [1,0,0,0]
word_Let = [0,1,0,0]
word_to = [0,0,1,0]
word_go = [0,0,0,1]

In [3]:
word2vec = np.array(
    [[1.16, -0.77], 
     [-0.27,0.82],
     [-2.19, 0.89],
     [3.5, -1.74]]
)
word2vecT = np.transpose(word2vec)

In [4]:
sentence_matrix = np.array(
    [word_SOS,
     word_Let,
     word_go]
)

# Encoder

### Step 1: Word embedding

In [5]:
result1_1 = np.dot(sentence_matrix, word2vec)
np.around(result1_1, decimals=2)

array([[ 1.16, -0.77],
       [-0.27,  0.82],
       [ 3.5 , -1.74]])

### Step 2: Add position

In [6]:
position_matrix = np.array(
    [[0, 1],
     [0.84, 0.54],
     [0.91, -0.42]]
)
result1_2 = result1_1+position_matrix
np.around(result1_2, decimals=2)

array([[ 1.16,  0.23],
       [ 0.57,  1.36],
       [ 4.41, -2.16]])

### Step 3: Transformer

In [7]:
W_Q = np.array(
    [[2.22, 0.41],
     [0.17, -0.51]]
)
W_K = np.array(
    [[-1.82, 0.57],
     [1.36, -0.38]]
)
W_V = np.array(
    [[-0.43, -0.59],
     [1.33, -2.15]]
)

In [8]:
result1_3_Q = np.dot(result1_2, W_Q)
result1_3_K = np.dot(result1_2, W_K)
result1_3_V = np.dot(result1_2, W_V)

In [9]:
result1_3_QK = np.dot(result1_3_Q, np.transpose(result1_3_K))/np.sqrt(2)

In [10]:
def softmax(row):
    exp_row = np.exp(row)
    sum_exp = np.sum(exp_row)
    return exp_row / sum_exp
result1_3_QK_softmax = np.apply_along_axis(softmax, 1, result1_3_QK)
np.around(result1_3_QK_softmax, decimals=2)

array([[0.01, 0.99, 0.  ],
       [0.05, 0.95, 0.  ],
       [0.  , 1.  , 0.  ]])

In [11]:
result1_3 = np.dot(result1_3_QK_softmax, result1_3_V)
np.around(result1_3, decimals=2)

array([[ 1.55, -3.24],
       [ 1.48, -3.16],
       [ 1.56, -3.26]])

### Step 4: Add resuidual connection

In [12]:
result1_4 = result1_3 + result1_2
np.around(result1_4, decimals=2)

array([[ 2.71, -3.01],
       [ 2.05, -1.8 ],
       [ 5.97, -5.42]])

# Decoder

In [ ]:
word_SOS2 = [1,0,0,0,0]
word_ir = [0,1,0,0,0]
word_vamos = [0,0,1,0,0]
word_y = [0,0,0,1,0]
word_EOS2 = [0,0,0,0,1]

word2vec_spanish = np.array(
    [[-2.53, -0.97], 
     [1.27,2.17],
     [0.71, 0.73],
     [0.58, 0.69],
     [-1.39, 0.76]]
)
word2vec_spanishT = np.transpose(word2vec)

### Step 1: Word embedding

In [14]:
result2_1 = np.dot(word_SOS2, word2vec_spanish)
np.around(result2_1, decimals=2)

array([-2.53, -0.97])

In [ ]:
test